### ISSUE TITLE
n8nworker not working with the new version of n8n 1.64.0 

### ISSUE THREAD

**Issue by axxonet-01** [flipswitchingmonkey/n8nworkerview#2]
Hope all is well.
is it that the pubsub mechanism with redis has changed ?
workers are not showing up in the new version.

**Comment by kent-1** [comment]
Nothing is publish now in channel n8n.commands and n8n.worker-response

**Comment by flipswitchingmonkey** [comment]
This was created during a hackathon at n8n and I haven't been working there for a while now, so have not touched it since. I'll see if I find the time to look into what's wrong...

Edit: At a quick glance, looks like the messaging was reworked.

**Comment by flipswitchingmonkey** [comment]
Turns out these messages are now enterprise license only. Sorry. 👎
